update init

diff --git a/templates/default/init.sh.erb b/templates/default/init.sh.erb
--- a/templates/default/init.sh.erb
+++ b/templates/default/init.sh.erb
@@ -1,67 +1,93 @@
 #!/bin/sh
 #
-# nginx
+# nginx        Startup script for nginx
 #
-# chkconfig:   - 57 47
-# description: nginx
-# processname:  nginx
-# config:       /etc/sysconfig/nginx
+# chkconfig: - 85 15
+# processname: nginx
+# config: /etc/nginx/nginx.conf
+# config: /etc/sysconfig/nginx
+# pidfile: /var/run/nginx.pid
+# description: nginx is an HTTP and reverse proxy server
 #
+### BEGIN INIT INFO
+# Provides: nginx
+# Required-Start: $local_fs $remote_fs $network
+# Required-Stop: $local_fs $remote_fs $network
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: start and stop nginx
+### END INIT INFO
 
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-# Source networking configuration.
-. /etc/sysconfig/network
+if [ -L $0 ]; then
+    initscript=`/bin/readlink -f $0`
+else
+    initscript=$0
+fi
 
-# Check that networking is up.
-[ "$NETWORKING" = "no" ] && exit
-exec=/usr/sbin/nginx
-prog=$(basename $exec)
+sysconfig=`/bin/basename $initscript`
 
-# default options, overruled by items in sysconfig
-NGINX_GLOBAL=""
+if [ -f /etc/sysconfig/$sysconfig ]; then
+    . /etc/sysconfig/$sysconfig
+fi
 
-[ -e /etc/sysconfig/nginx ] && . /etc/sysconfig/nginx
-
-lockfile=/var/lock/subsys/nginx
+nginx=${NGINX-/usr/sbin/nginx}
+prog=`/bin/basename $nginx`
+conffile=${CONFFILE-/etc/nginx/nginx.conf}
+lockfile=${LOCKFILE-/var/lock/subsys/nginx}
+pidfile=${PIDFILE-/var/run/nginx.pid}
+SLEEPMSEC=${SLEEPMSEC-200000}
+UPGRADEWAITLOOPS=${UPGRADEWAITLOOPS-5}
+RETVAL=0
 
 start() {
-    [ -x $exec ] || exit 5
     echo -n $"Starting $prog: "
-    # if not running, start it up here, usually something like "daemon $exec"
-    options=""
-    if [ "${NGINX_GLOBAL}" != ""  ]; then
-        options="-g ${NGINX_GLOBAL}"
-    fi
-    $exec $options
-    retval=$?
+
+    daemon --pidfile=${pidfile} ${nginx} -c ${conffile}
+    RETVAL=$?
     echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+    [ $RETVAL = 0 ] && touch ${lockfile}
+    return $RETVAL
 }
 
 stop() {
     echo -n $"Stopping $prog: "
-    $exec -s stop
-    retval=$?
+    killproc -p ${pidfile} ${prog}
+    RETVAL=$?
     echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
-}
-
-restart() {
-    stop
-    start
+    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
 
 reload() {
     echo -n $"Reloading $prog: "
-    $exec -s reload
-    retval=$?
+    killproc -p ${pidfile} ${prog} -HUP
+    RETVAL=$?
     echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
+}
+
+upgrade() {
+    oldbinpidfile=${pidfile}.oldbin
+
+    configtest -q || return
+    echo -n $"Starting new master $prog: "
+    killproc -p ${pidfile} ${prog} -USR2
+    echo
+
+    for i in `/usr/bin/seq $UPGRADEWAITLOOPS`; do
+        /bin/usleep $SLEEPMSEC
+        if [ -f ${oldbinpidfile} -a -f ${pidfile} ]; then
+            echo -n $"Graceful shutdown of old $prog: "
+            killproc -p ${oldbinpidfile} ${prog} -QUIT
+            RETVAL=$?
+            echo
+            return
+        fi
+    done
+
+    echo $"Upgrade failed!"
+    RETVAL=1
 }
 
 configtest() {
@@ -75,37 +101,52 @@ configtest() {
         esac
         shift
     fi
-    ${exec} -t $FLAG
+    ${nginx} -t -c ${conffile} $FLAG
     RETVAL=$?
     return $RETVAL
 }
 
+rh_status() {
+    status -p ${pidfile} ${nginx}
+}
+
 # See how we were called.
 case "$1" in
-  start)
+    start)
+        rh_status >/dev/null 2>&1 && exit 0
         start
         ;;
-  stop)
+    stop)
         stop
         ;;
-  status)
-        status nginx
+    status)
+        rh_status
+        RETVAL=$?
         ;;
-  restart)
-        restart
+    restart)
+        configtest -q || exit $RETVAL
+        stop
+        start
         ;;
-  reload|force-reload)
+    upgrade)
+        rh_status >/dev/null 2>&1 || exit 0
+        upgrade
+        ;;
+    condrestart|try-restart)
+        if rh_status >/dev/null 2>&1; then
+            stop
+            start
+        fi
+        ;;
+    force-reload|reload)
         reload
         ;;
-  condrestart)
-        [ -f $lockfile ] && restart || :
-        ;;
-  configtest)
+    configtest)
         configtest
         ;;
-  *)
-        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|configtest}"
-        exit 1
+    *)
+        echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
+        RETVAL=2
 esac
 
-exit $?
+exit $RETVAL
